apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cnetmon
  namespace: cnetmon
  labels:
    k8s-app: cnetmon
spec:
  selector:
    matchLabels:
      name: cnetmon
  template:
    metadata:
      labels:
        name: cnetmon
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: cnetmon
          image: ctlptl-registry:5005/my-image
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cnetmon
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
