apiVersion: v1
kind: Service
metadata:
  name: cnetmon-tcp
  namespace: cnetmon
spec:
  clusterIP: None
  selector:
    name: cnetmon
  ports:
    - name: cnetmon
      protocol: TCP
      port: 7777
      targetPort: 7777
