name: cnetmon build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: src/go.sum

      - name: Build
        run: cd src && go build -ldflags="-w -s" -o ../out/cnetmon .

      - name: Test
        run: cd src &&  go test -v ./...

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cnetmon:$(date +%s)
